const elements = [{symbol:'H',name:'هیدروژن',number:1,shells:[1],fact:'هیدروژن سبک‌ترین عنصر جهان و یکی از اجزای آب است.'},{symbol:'He',name:'هلیم',number:2,shells:[2],fact:'هلیم گازی سبک و بی‌اثر است و در بادکنک‌ها استفاده می‌شود.'},{symbol:'Li',name:'لیتیم',number:3,shells:[2,1],fact:'لیتیم فلزی سبک است و در باتری‌های قابل شارژ کاربرد دارد.'},{symbol:'Be',name:'بریلیم',number:4,shells:[2,2],fact:'بریلیم فلزی سبک و محکم است و در فناوری‌های فضایی کاربرد دارد.'},{symbol:'B',name:'بور',number:5,shells:[2,3],fact:'بور در شیشه‌های مقاوم به گرما و بعضی شوینده‌ها پیدا می‌شود.'},{symbol:'C',name:'کربن',number:6,shells:[2,4],fact:'کربن در مداد، الماس و حتی بدن ما وجود دارد؛ عنصری با شکل‌های شگفت‌انگیز.'},{symbol:'N',name:'نیتروژن',number:7,shells:[2,5],fact:'بخش بزرگی از هوای اطراف ما را نیتروژن تشکیل می‌دهد.'},{symbol:'O',name:'اکسیژن',number:8,shells:[2,6],fact:'اکسیژن برای نفس کشیدن ما ضروری است و حدود یک‌پنجم هوا را می‌سازد.'},{symbol:'F',name:'فلوئور',number:9,shells:[2,7],fact:'فلوئور واکنش‌پذیرترین نافلز است و در خمیردندان‌ها به شکل ترکیب دیده می‌شود.'},{symbol:'Ne',name:'نئون',number:10,shells:[2,8],fact:'نئون در لامپ‌های تبلیغاتی نور قرمز و نارنجی درخشان تولید می‌کند.'},{symbol:'Na',name:'سدیم',number:11,shells:[2,8,1],fact:'سدیم فلزی بسیار واکنش‌پذیر است و همراه کلر در نمک خوراکی دیده می‌شود.'},{symbol:'Mg',name:'منیزیم',number:12,shells:[2,8,2],fact:'منیزیم در بدن و گیاهان مهم است و در مرکز مولکول کلروفیل قرار دارد.'},{symbol:'Al',name:'آلومینیوم',number:13,shells:[2,8,3],fact:'آلومینیوم سبک و مقاوم است و در قوطی‌ها، هواپیماها و فویل‌ها کاربرد دارد.'},{symbol:'Si',name:'سیلیسیم',number:14,shells:[2,8,4],fact:'سیلیسیم ماده‌ای مهم در شن و ماسه و تراشه‌های الکترونیکی است.'},{symbol:'P',name:'فسفر',number:15,shells:[2,8,5],fact:'فسفر برای استخوان‌ها و سلول‌های بدن ضروری است.'},{symbol:'S',name:'گوگرد',number:16,shells:[2,8,6],fact:'گوگرد جامدی زردرنگ است و در بعضی چشمه‌های آتشفشانی یافت می‌شود.'},{symbol:'Cl',name:'کلر',number:17,shells:[2,8,7],fact:'کلر در ضدعفونی آب و همراه سدیم در نمک خوراکی کاربرد دارد.'},{symbol:'Ar',name:'آرگون',number:18,shells:[2,8,8],fact:'آرگون گازی بی‌اثر است و برای محافظت از فلز داغ در لامپ‌ها استفاده می‌شود.'},{symbol:'K',name:'پتاسیم',number:19,shells:[2,8,8,1],fact:'پتاسیم برای کارکرد ماهیچه‌ها و پیام‌های عصبی بدن مهم است.'},{symbol:'Ca',name:'کلسیم',number:20,shells:[2,8,8,2],fact:'کلسیم به ساخت استخوان‌ها و دندان‌های محکم کمک می‌کند.'}];
const faDigits = value => String(value).replace(/[0-9]/g, digit => '۰۱۲۳۴۵۶۷۸۹'[digit]);
const $ = selector => document.querySelector(selector);
function addFourthShell(){ $('.shell-guide').insertAdjacentHTML('beforeend','<div class="shell-choice" data-shell-choice="4"><div><b>لایه چهارم</b><small>N | حداکثر ۲</small></div><div class="stepper-controls"><button class="step-button" data-step="up" data-shell="4" type="button" aria-label="افزودن الکترون به لایه چهارم">▲</button><strong id="shellFourCount">۰</strong><button class="step-button" data-step="down" data-shell="4" type="button" aria-label="کم کردن الکترون از لایه چهارم">▼</button></div></div>'); $('.atom-board').insertAdjacentHTML('afterbegin','<div class="atom-label label-four">لایه چهارم <b>N</b></div>'); $('.bohr-atom').insertAdjacentHTML('beforeend','<div class="shell shell-4" data-shell="4" role="button" tabindex="0" aria-label="افزودن الکترون به لایه چهارم"><div class="electrons" id="shellFourElectrons"></div></div>'); }
addFourthShell();
let playerName = ''; let selected = elements[0]; let score = 0; let streak = 0; let shellCounts = [0,0,0,0]; let activeShell = 1;
const welcome = $('#welcomeScreen'); const game = $('#gameScreen'); const result = $('#resultScreen');
$('#nameForm').addEventListener('submit', event => { event.preventDefault(); const value = $('#playerName').value.trim(); if (!value) return; playerName = value; startGame(); });
function startGame(){ score=0; streak=0; selected=elements[Math.floor(Math.random()*elements.length)]; updateHeader(); $('#greeting').textContent=`سلام ${playerName}!`; $('#levelNumber').textContent='۱'; $('#levelHint').textContent='اولین نشانه‌ی عنصر را پیدا کن.'; $('#progressBar').style.width='33.333%'; setText(); welcome.classList.add('hidden'); result.classList.add('hidden'); game.classList.remove('hidden'); showChallenge('challengeSymbol'); }
function updateHeader(){ $('#scoreValue').textContent=faDigits(score); $('#streakValue').textContent=faDigits(streak); }
function setText(){ $('#symbolPrompt').textContent=selected.symbol; $('#chosenSymbol').textContent=selected.symbol; $('#chosenName').textContent=selected.name; $('#bohrElementName').textContent=selected.name; $('#bohrNucleusSymbol').textContent=selected.symbol; $('#bohrNucleusNumber').textContent=faDigits(selected.number); $('#factText').textContent=selected.fact; }
function showChallenge(id){ ['challengeSymbol','challengeAtomic','challengePeriodic','challengeBohr'].forEach(name=>$('#'+name).classList.toggle('hidden',name!==id)); if(id==='challengeSymbol') buildSymbolOptions(); if(id==='challengeAtomic') buildAtomicOptions(); if(id==='challengePeriodic') buildPeriodicTable(); if(id==='challengeBohr') resetBohr(); }
function makeOption(label, handler){ const button=document.createElement('button'); button.type='button'; button.className='option'; button.textContent=label; button.addEventListener('click',handler); return button; }
function buildSymbolOptions(){ const container=$('#symbolOptions'); container.innerHTML=''; const distractors=elements.filter(item=>item.symbol!==selected.symbol).sort(()=>Math.random()-.5).slice(0,3); const options=[selected,...distractors].sort(()=>Math.random()-.5); options.forEach(item=>container.append(makeOption(item.name,()=>checkSymbol(item.name)))); $('#symbolFeedback').textContent=''; }
function checkSymbol(name){ const correct=name===selected.name; const buttons=[...$('#symbolOptions').children]; buttons.forEach(button=>{button.classList.remove('wrong');if(button.textContent===name&&!correct)button.classList.add('wrong')}); if(correct){buttons.forEach(button=>{button.disabled=true;if(button.textContent===selected.name)button.classList.add('correct')});score+=10;streak++; $('#symbolFeedback').textContent='آفرین! حالا یک قدم به ساختن اتم نزدیک‌تری.';setTimeout(()=>{ $('#levelNumber').textContent='۲'; $('#levelHint').textContent='دانستن عدد اتمی، کلید ورود به هسته است.'; $('#progressBar').style.width='66.666%'; showChallenge('challengeAtomic');},700)}else{$('#symbolFeedback').textContent='این گزینه درست نیست؛ دوباره تلاش کن.';$('#symbolFeedback').classList.add('error');streak=0} updateHeader();}
function buildAtomicOptions(){const container=$('#atomicOptions');container.innerHTML='';const values=[selected.number,...elements.map(item=>item.number).filter(number=>number!==selected.number),2].slice(0,4).sort(()=>Math.random()-.5);values.forEach(value=>container.append(makeOption(faDigits(value),()=>checkAtomic(value))));$('#atomicFeedback').textContent='';$('#atomicFeedback').classList.remove('error');}
function checkAtomic(value){const correct=value===selected.number;const buttons=[...$('#atomicOptions').children];buttons.forEach(button=>{button.classList.remove('wrong');if(button.textContent===faDigits(value)&&!correct)button.classList.add('wrong')});if(correct){buttons.forEach(button=>{button.disabled=true;if(button.textContent===faDigits(selected.number))button.classList.add('correct')});score+=15;streak++;$('#atomicFeedback').textContent='عالیه! تعداد پروتون‌ها را درست پیدا کردی.';setTimeout(()=>{$('#levelNumber').textContent='۳';$('#levelHint').textContent='عنصر را روی جدول تناوبی پیدا کن.';$('#progressBar').style.width='85%';showChallenge('challengePeriodic');},700)}else{$('#atomicFeedback').textContent='این عدد درست نیست؛ دوباره تلاش کن.';$('#atomicFeedback').classList.add('error');streak=0}updateHeader();}
function buildPeriodicTable(){const table=$('#periodicTable');table.innerHTML='';const positions={1:[1,1],2:[1,18],3:[2,1],4:[2,2],5:[2,13],6:[2,14],7:[2,15],8:[2,16],9:[2,17],10:[2,18],11:[3,1],12:[3,2],13:[3,13],14:[3,14],15:[3,15],16:[3,16],17:[3,17],18:[3,18],19:[4,1],20:[4,2]};elements.forEach(element=>{const cell=document.createElement('div');const [period,group]=positions[element.number];cell.className=`periodic-cell${element.number===selected.number?' selected':''}`;cell.style.gridColumn=group;cell.style.gridRow=period;cell.innerHTML=`<small>${faDigits(element.number)}</small><strong>${element.symbol}</strong><span>${element.name}</span>`;cell.title=`${element.name}، عدد اتمی ${faDigits(element.number)}`;table.append(cell)});$('#periodicElementName').textContent=selected.name;$('#periodicSelectedSymbol').textContent=selected.symbol;$('#periodicSelectedText').textContent=`${selected.name} | عدد اتمی ${faDigits(selected.number)}`;}
function resetBohr(){shellCounts=[0,0,0,0];activeShell=1;[1,2,3,4].forEach(shell=>{renderShell(shell);setActiveShell(shell,shell===1)});updateShellCounts();$('#bohrFeedback').textContent='مدل پاک شد؛ از لایه اول شروع کن.';$('#bohrFeedback').classList.remove('error');}
function renderShell(shell){const names=['One','Two','Three','Four'];const container=$(`#shell${names[shell-1]}Electrons`);container.innerHTML='';for(let index=0;index<shellCounts[shell-1];index++){const electron=document.createElement('i');electron.className='electron';container.append(electron)}}
function updateShellCounts(){['One','Two','Three','Four'].forEach((name,index)=>{$(`#shell${name}Count`).textContent=faDigits(shellCounts[index])})}
function setActiveShell(shell,isActive=true){if(isActive)activeShell=shell;document.querySelectorAll('.shell-choice,.shell').forEach(item=>item.classList.toggle('active',Number(item.dataset.shellChoice||item.dataset.shell)===activeShell));}
document.querySelectorAll('.shell-choice').forEach(choice=>choice.addEventListener('click',event=>{if(!event.target.closest('.step-button'))setActiveShell(Number(choice.dataset.shellChoice))}));
document.querySelectorAll('.step-button').forEach(button=>button.addEventListener('click',()=>{const shell=Number(button.dataset.shell);setActiveShell(shell);addElectron(shell,button.dataset.step==='up'?1:-1)}));
function addElectron(shell,change){const capacities=[2,8,8,2];const max=capacities[shell-1];const nextCount=Math.max(0,Math.min(max,shellCounts[shell-1]+change));if(nextCount===shellCounts[shell-1]){const message=change>0?`این لایه بیشتر از ${faDigits(max)} الکترون نمی‌گیرد.`:'تعداد الکترون‌های این لایه نمی‌تواند کمتر از صفر باشد.';$('#bohrFeedback').textContent=message;$('#bohrFeedback').classList.add('error');return}shellCounts[shell-1]=nextCount;renderShell(shell);updateShellCounts();$('#bohrFeedback').textContent=change>0?`یک الکترون به لایه ${faDigits(shell)} اضافه شد.`:`یک الکترون از لایه ${faDigits(shell)} کم شد.`;$('#bohrFeedback').classList.remove('error');}
$('#resetBohr').addEventListener('click',resetBohr);
$('#continueToBohr').addEventListener('click',()=>{$('#levelNumber').textContent='۴';$('#levelHint').textContent='حالا وقت ساختن مدل بور است.';$('#progressBar').style.width='100%';showChallenge('challengeBohr');});
$('#checkBohr').addEventListener('click',()=>{const correct=selected.shells.every((count,index)=>count===shellCounts[index])&&shellCounts.slice(selected.shells.length).every(count=>count===0);if(correct){score+=25;streak++;updateHeader();$('#bohrFeedback').textContent='مدل بور تو دقیق و کامل است!';setTimeout(showResult,700)}else{$('#bohrFeedback').textContent=`هنوز کامل نشده؛ ${faDigits(selected.number)} الکترون را در لایه‌ها پخش کن.`;$('#bohrFeedback').classList.add('error')}});
function showResult(){$('#finalScore').textContent=faDigits(score);$('#resultName').textContent=playerName;game.classList.add('hidden');result.classList.remove('hidden');}
$('#restartButton').addEventListener('click',startGame);$('#changeNameButton').addEventListener('click',()=>{result.classList.add('hidden');welcome.classList.remove('hidden');$('#playerName').focus()});
